### PR TITLE
Updated to support Mambu 3.9 API changes

### PR DESCRIPTION
**Pull request by mdanilkis**
1. MBU-7336,  Create Group APIs
1a also, included code for MBU-7337 -Edit Groups API. NOTE: MBU-7337
will be now supported by Mambu in 3.10 only. Added TODOs to test when
ready
ClientService
2. MBU-7351 - Get Group Roles  and Get Details for Group Role APIs
ClientService
3.MBU-7061 - Get Client Types API (for Clients and for Groups) API
ClientService
4. MBU-7312, MBU-7313 - Client Profile Picture and Signature: APIs to
Store, Retrieve and Delete
ClientService, DocumentService
ServiceHelper notes: moved  makeParamsForDocumentJson() to ServiceHelper
DemoUtil: moved the encodeFileIntoBase64String() to DemoUtil from
DemoTestDocuments
5. MBU-6789, MBU-7676-  Get Repayments Schedule preview for a loan
product API
LoanService, ServiceHelper
6. MBU-7758 - Patch loan account terms API
LoanService, ServiceHelper
7. MBU-6813 - Update loan account repayments API
RepaymentsService
8. MBU-7189 - Undo loan account disbursement API
LoanService
9.   MBU-7034 - Custom Fields - refactoring to support client types.
Updated demo programs
DemoTestOrganizationService

10. MBU-7467 -  Updated comments only: allow username, key to id to be
used in place of username for getting Tasks
      MBU-6908 - Updated comments only: allow user key and id for
updating custom fields for the user

11. Enhanced DemoUtil and DemoTest to provide more helper methods for testing and
runs automation
- created helpers to run a sequence of API tests for specific accounts and products
- created helpers to create new accounts to be consistent with the
tested product type
- created helpers to create custom fields for accounts and clients/groups to be valid
for their product or client role
- rearranged some test cases to allow for higher probability of the
successful end-to-end runs of a demo test program

12. Updated Demo programs to test new APIs.

Miscellaneous:
13. Updated Maven pom file to use 3.9 model  jar and to build
Mambu-Java-3.9-bin.jar
14. Added missing wrapper for Delete Document API (available since 3.3,
see MBU-3526 )
DocumentsService
15. Updated ApiDefinition and ServiceExecutor to support new APIs
Added new definitions: GET_OWNED_ENTITY, PATCH_OWNED_ENTITIES.,
PATCH_JSON
16. Removed unused class util/APIExceptionData.java. This class was
never used and is not needed.  Mambu’s ReturnCode enum class can be
used instead.
Removed an unused constructor in MambuApiResponseMessage referencing
this class.
17. Deprecated ACCOUNT_TYPE enum in APIData class.  Mambu’s existent
Account.Type class (from the model) should be used instead.
Updated Savings Service to use Mambu’s Account.Type.  Deprecated
original methods using ACCOUNT_TYPE.
ApiData, SavingsService
18. TaskSerice  correction: renamed getTasks() to getTask()
19. RequestExecutorImpl.java - updated logging JSON data to better
handle encoded content for profile picture/signature API
20. Updated RAEDME file

### CODE REVIEW

**Comment by thobach** [comment]
Just a general comment on the ClientService, I think it makes sense to move the group methods from there into a separate GroupService.

**Comment by mdanilkis** [comment]
Sure, we can discuss creating a separate GroupService. But it may have it's downside too: many methods are pretty much identical for clients and groups, so it could result in more code overall and more testing.

**Comment by thobach** [comment]
Maybe we can leverage inheritance using an abstract service class that
capsulates common behaviour. For SDK users it doesn't feel very natural to
create groups using the ClientService and the ClientService is also quite
large already.

Just some thoughts for future improvements ;)

Cheers,

Thomas

--
Thomas Bachmann
Reinickstr. 7
01309 Dresden

Telefon: 0176 - 78 000 535
Webseite: http://www.thobach.de
Twitter: http://twitter.com/thobach
Projekt: http://www.cocktailberater.de
Arbeit: http://www.mambu.com

**Comment by thobach** [comment]
Thanks Michael for all your work!

**Pull request merged**
